# Chapter 2: Statistical Learning — Lab
---
> **Context**: This notebook follows the introductory lab of *Introduction to Statistical Learning with Python (ISLP)*.  
> **Objective**: Gain proficiency in the Python environment, data ingestion, and Exploratory Data Analysis (EDA).

---
## 2.3.2 Basic Commands
Testing basic Python output and variable handling.

### 1. Basic Arithmetic and String Formatting
Testing standard Python output and string concatenation using `f-strings` for better readability.

In [28]:
# f-string formatting 
n_vars = 11
print(f"Fit a model with {n_vars} variables")

# Basic arithmetic and string concatenation
print(f"Arithmetic test (3+5): {3 + 5}")
print("Hello" + " " + "world")

Fit a model with 11 variables
Arithmetic test (3+5): 8
Hello world


### 2. Introspection Tools
Using `?` to access the docstring and help menu for built-in functions. 
*Note: This is an interactive command for development.*

In [29]:
# Uncomment the line below to view the print function documentation
# print?

### 3. List Operations and Concatenation
Defining vectors as Python lists. Note that the `+` operator in standard Python performs **concatenation**, not element-wise addition.

In [30]:
# Defining two numeric lists
x = [3, 4, 5]
y = [4, 9, 7]

# Displaying x and its concatenation with y
print(f"List x: {x}")
print(f"Concatenated lists (x + y): {x + y}")

List x: [3, 4, 5]
Concatenated lists (x + y): [3, 4, 5, 4, 9, 7]


---
## 2.3.3 Introduction to Numerical Python (NumPy)
`NumPy` is the foundational library for scientific computing in Python. Unlike standard lists, NumPy arrays enable **vectorization**, allowing for high-performance mathematical operations on large datasets.

### 1. Array Creation and Metadata
In this section, we transition from standard Python lists to **NumPy arrays (ndarrays)**. We explore array creation, data types (`dtype`), and structural attributes like `shape` and `ndim`.

In [56]:
# 1. Import the NumPy library
import numpy as np

# 2. Create two NumPy arrays from the lists x and y
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

# 3. Display the arrays and their element-wise sum
print(f"x + y: {x + y}")

# 4. Create a 2D NumPy array (matrix) and display it
x = np.array([[1, 2], [3, 4]])
print(f"Matrix x:\n{x}")

# 5. Display the number of dimensions of the array
print(f"Dimensions: {x.ndim}")

# 6. Display the shape of the array
print(f"Shape: {x.shape}")

# 7. Display the data type of the array
print(f"Dtype: {x.dtype}")

# 8. Create a new array with mixed data types and display its data type
print(f"Mixed dtype: {np.array([[1, 2], [3.0, 4]]).dtype}")

# 9. View the documentation for the NumPy array function
# np.array?

# 10. Create a new array with a specified data type and display its data type
print(f"Forced float dtype: {np.array([[1, 2], [3, 4]], float).dtype}")

# 11. Display the shape of the original array x
print(f"Current shape: {x.shape}")

x + y: [ 7 13 12]
Matrix x:
[[1 2]
 [3 4]]
Dimensions: 2
Shape: (2, 2)
Dtype: int64
Mixed dtype: float64
Forced float dtype: float64
Current shape: (2, 2)


### 2. Reshaping and Memory Indexing
Numerical arrays can be reshaped to fit model requirements. It is critical to note that reshaping often creates a **view**, meaning modifications to the reshaped array will affect the original data.

In [57]:
# 12. Create a new array and compute its sum using the NumPy sum function
x = np.array([1, 2, 3, 4])
print(f"Sum: {x.sum()}")

# 13. Re-assign and compute sum using np.sum()
x = np.array([1, 2, 3, 4])
print(f"NP Sum: {np.sum(x)}")

# 14. Create an array for reshaping
x = np.array([1, 2, 3, 4, 5, 6])
print('Beginning x:\n', x)

# 15. Reshape the array x to (2, 3)
x_reshape = x.reshape((2, 3))
print('Reshaped x:\n', x_reshape)

# 16. Access element (row 0, col 0)
print(f"Element [0,0]: {x_reshape[0, 0]}")

# 17. Access element (row 1, col 2)
print(f"Element [1,2]: {x_reshape[1, 2]}")

# 18. Demonstrate that modifying a view modifies the original array
print('x before modification:\n', x)
x_reshape[0, 0] = 5
print('x after modifying x_reshape[0,0]:\n', x)

Sum: 10
NP Sum: 10
Beginning x:
 [1 2 3 4 5 6]
Reshaped x:
 [[1 2 3]
 [4 5 6]]
Element [0,0]: 1
Element [1,2]: 6
x before modification:
 [1 2 3 4 5 6]
x after modifying x_reshape[0,0]:
 [5 2 3 4 5 6]


### Tuples vs. Arrays: Understanding Immutability
Unlike NumPy arrays, Python **tuples** are immutable. Attempting to modify them will result in a `TypeError`.

In [58]:
# 19-20. Demonstrate Tuple immutability
my_tuple = (3, 4, 5)
try:
    my_tuple[0] = 2
except TypeError as e:
    print(f"Expected Error: {e}")

# 21. Display attributes and Transpose
print(f"Shape: {x_reshape.shape}, Ndim: {x_reshape.ndim}")
print(f"Transpose:\n{x_reshape.T}")

Expected Error: 'tuple' object does not support item assignment
Shape: (2, 3), Ndim: 2
Transpose:
[[5 4]
 [2 5]
 [3 6]]


### Element-wise Mathematical Operations
NumPy provides optimized functions for universal transformations (Square root, Exponentiation).

In [59]:
# 22. Square root
print(f"Sqrt: {np.sqrt(x)}")

# 23. Square
print(f"Square: {x**2}")

# 24. Sqrt using exponentiation
print(f"Sqrt (x**0.5): {x**0.5}")

Sqrt: [2.23606798 1.41421356 1.73205081 2.         2.23606798 2.44948974]
Square: [25  4  9 16 25 36]
Sqrt (x**0.5): [2.23606798 1.41421356 1.73205081 2.         2.23606798 2.44948974]


### Random Number Generation and Correlation
Statistical simulations require random draws. We use seeds and the `default_rng` to ensure our research is reproducible.

In [60]:
# 25. Standard Normal Distribution (n=50)
x = np.random.normal(size=50)

# 26. Adding noise to signal
y = x + np.random.normal(loc=50, scale=1, size=50)

# 27. Correlation coefficient
print(f"Correlation Matrix:\n{np.corrcoef(x, y)}")

# 28. Unseeded vs. Seeded Randomness
print(f"Random set 1: {np.random.normal(scale=5, size=2)}")
print(f"Random set 2: {np.random.normal(scale=5, size=2)}")

# 29. Reproducibility using default_rng and seeds
rng = np.random.default_rng(1303)
print(f"RNG 1: {rng.normal(scale=5, size=2)}")
rng2 = np.random.default_rng(1303)
print(f"RNG 2 (Same seed): {rng2.normal(scale=5, size=2)}")

Correlation Matrix:
[[1.         0.78249551]
 [0.78249551 1.        ]]
Random set 1: [1.0838527  8.33265082]
Random set 2: [-3.49806977 -1.03721351]
RNG 1: [ 4.09482632 -1.07485605]
RNG 2 (Same seed): [ 4.09482632 -1.07485605]


### Descriptive Statistics and Matrix Operations
Calculating Mean, Variance, and Standard Deviation. We also perform operations across specific **axes** (0 for columns, 1 for rows).

In [61]:
# 30. Generating data and checking Means
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
print(f"Mean (function vs method): {np.mean(y)}, {y.mean()}")

# 31. Variance check
print(f"Variance check: {np.var(y)}, {y.var()}, {np.mean((y - y.mean())**2)}")

# 32. Standard Deviation
print(f"Std Dev: {np.sqrt(np.var(y))}, {np.std(y)}")

# 33. Matrix generation (10x3)
X = rng.standard_normal((10, 3))

# 34-35. Axis operations (Column means)
print(f"Mean across axis 0: {X.mean(axis=0)}")
print(f"Mean across axis 0 (short syntax): {X.mean(0)}")

Mean (function vs method): -0.1126795190952861, -0.1126795190952861
Variance check: 2.7243406406465125, 2.7243406406465125, 2.7243406406465125
Std Dev: 1.6505576756498128, 1.6505576756498128
Mean across axis 0: [ 0.15030588  0.14030961 -0.34238602]
Mean across axis 0 (short syntax): [ 0.15030588  0.14030961 -0.34238602]
